# Generated by Django 5.0.6 on 2026-07-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('fr', 'French'), ('es', 'Spanish')], max_length=2)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat.message')),
            ],
            options={
                'unique_together': {('message', 'target_language')},
            },
        ),
    ]
